### PR TITLE
Create B10730228_Rurushu.txt

### PR DESCRIPTION
**Pull request by Ruru-Shu**
我要pull

### CODE REVIEW

**Comment by Ruru-Shu** [comment]
Leave a comment

**Comment by Ruru-Shu** [comment]
I want to merge now.

**Comment by Ruru-Shu** [comment]
Do not stop me

**Comment by Ruru-Shu** [comment]
What are you doing

**Comment by Ruru-Shu** [comment]
Hey man

**Comment by Hsun-Yu** [comment]
ohhh I am so sad. you do it by your self you are not a master

**Pull request merged**
